set(_CATKIN_CURRENT_PACKAGE "promobot_app_printer5")
set(promobot_app_printer5_VERSION "2.0.0")
set(promobot_app_printer5_MAINTAINER "promobot <info@promo-bot.ru>")
set(promobot_app_printer5_PACKAGE_FORMAT "1")
set(promobot_app_printer5_BUILD_DEPENDS "libqtpromobot" "libqtapplicationbase")
set(promobot_app_printer5_BUILD_EXPORT_DEPENDS "libqtpromobot" "libqtapplicationbase")
set(promobot_app_printer5_BUILDTOOL_DEPENDS "catkin")
set(promobot_app_printer5_BUILDTOOL_EXPORT_DEPENDS )
set(promobot_app_printer5_EXEC_DEPENDS "libqtpromobot" "libqtapplicationbase")
set(promobot_app_printer5_RUN_DEPENDS "libqtpromobot" "libqtapplicationbase")
set(promobot_app_printer5_TEST_DEPENDS )
set(promobot_app_printer5_DOC_DEPENDS )
set(promobot_app_printer5_URL_WEBSITE "http://promo-bot.ru")
set(promobot_app_printer5_URL_BUGTRACKER "")
set(promobot_app_printer5_URL_REPOSITORY "")
set(promobot_app_printer5_DEPRECATED "")