set(_CATKIN_CURRENT_PACKAGE "promobot_app_template_qml")
set(promobot_app_template_qml_VERSION "2.0.0")
set(promobot_app_template_qml_MAINTAINER "promobot <info@promo-bot.ru>")
set(promobot_app_template_qml_PACKAGE_FORMAT "1")
set(promobot_app_template_qml_BUILD_DEPENDS "libqtpromobot" "libqtapplicationbase" "libqtapplicationwidgets")
set(promobot_app_template_qml_BUILD_EXPORT_DEPENDS "libqtpromobot" "libqtapplicationbase" "libqtapplicationwidgets")
set(promobot_app_template_qml_BUILDTOOL_DEPENDS "catkin")
set(promobot_app_template_qml_BUILDTOOL_EXPORT_DEPENDS )
set(promobot_app_template_qml_EXEC_DEPENDS "libqtpromobot" "libqtapplicationbase" "libqtapplicationwidgets")
set(promobot_app_template_qml_RUN_DEPENDS "libqtpromobot" "libqtapplicationbase" "libqtapplicationwidgets")
set(promobot_app_template_qml_TEST_DEPENDS )
set(promobot_app_template_qml_DOC_DEPENDS )
set(promobot_app_template_qml_URL_WEBSITE "http://promo-bot.ru")
set(promobot_app_template_qml_URL_BUGTRACKER "")
set(promobot_app_template_qml_URL_REPOSITORY "")
set(promobot_app_template_qml_DEPRECATED "")