set(_CATKIN_CURRENT_PACKAGE "promobot_app_OveNewSdk4")
set(promobot_app_OveNewSdk4_VERSION "2.0.0")
set(promobot_app_OveNewSdk4_MAINTAINER "Pincu Catalin <pincu.catalin@yahoo.com>")
set(promobot_app_OveNewSdk4_PACKAGE_FORMAT "1")
set(promobot_app_OveNewSdk4_BUILD_DEPENDS "libqtpromobot" "libqtpromobotwidgets" "libqtapplicationbase" "libqtapplicationwidgets" "QtPrintSupport")
set(promobot_app_OveNewSdk4_BUILD_EXPORT_DEPENDS "libqtpromobot" "libqtpromobotwidgets" "libqtapplicationbase" "libqtapplicationwidgets" "QtPrintSupport")
set(promobot_app_OveNewSdk4_BUILDTOOL_DEPENDS "catkin")
set(promobot_app_OveNewSdk4_BUILDTOOL_EXPORT_DEPENDS )
set(promobot_app_OveNewSdk4_EXEC_DEPENDS "libqtpromobot" "libqtpromobotwidgets" "libqtapplicationbase" "libqtapplicationwidgets" "QtPrintSupport")
set(promobot_app_OveNewSdk4_RUN_DEPENDS "libqtpromobot" "libqtpromobotwidgets" "libqtapplicationbase" "libqtapplicationwidgets" "QtPrintSupport")
set(promobot_app_OveNewSdk4_TEST_DEPENDS )
set(promobot_app_OveNewSdk4_DOC_DEPENDS )
set(promobot_app_OveNewSdk4_URL_WEBSITE "https://bucharestrobots.com/")
set(promobot_app_OveNewSdk4_URL_BUGTRACKER "")
set(promobot_app_OveNewSdk4_URL_REPOSITORY "")
set(promobot_app_OveNewSdk4_DEPRECATED "")