set(_CATKIN_CURRENT_PACKAGE "promobot_example_app_printer")
set(promobot_example_app_printer_VERSION "2.0.0")
set(promobot_example_app_printer_MAINTAINER "promobot <info@promo-bot.ru>")
set(promobot_example_app_printer_PACKAGE_FORMAT "1")
set(promobot_example_app_printer_BUILD_DEPENDS "libqtpromobot" "libqtapplicationbase")
set(promobot_example_app_printer_BUILD_EXPORT_DEPENDS "libqtpromobot" "libqtapplicationbase")
set(promobot_example_app_printer_BUILDTOOL_DEPENDS "catkin")
set(promobot_example_app_printer_BUILDTOOL_EXPORT_DEPENDS )
set(promobot_example_app_printer_EXEC_DEPENDS "libqtpromobot" "libqtapplicationbase")
set(promobot_example_app_printer_RUN_DEPENDS "libqtpromobot" "libqtapplicationbase")
set(promobot_example_app_printer_TEST_DEPENDS )
set(promobot_example_app_printer_DOC_DEPENDS )
set(promobot_example_app_printer_URL_WEBSITE "http://promo-bot.ru")
set(promobot_example_app_printer_URL_BUGTRACKER "")
set(promobot_example_app_printer_URL_REPOSITORY "")
set(promobot_example_app_printer_DEPRECATED "")