set(_CATKIN_CURRENT_PACKAGE "promobot_example_app_dialog")
set(promobot_example_app_dialog_VERSION "2.0.0")
set(promobot_example_app_dialog_MAINTAINER "promobot <info@promo-bot.ru>")
set(promobot_example_app_dialog_PACKAGE_FORMAT "1")
set(promobot_example_app_dialog_BUILD_DEPENDS "libqtpromobot" "libqtapplicationbase" "libqtpromobotdialogmodule")
set(promobot_example_app_dialog_BUILD_EXPORT_DEPENDS "libqtpromobot" "libqtapplicationbase" "libqtpromobotdialogmodule")
set(promobot_example_app_dialog_BUILDTOOL_DEPENDS "catkin")
set(promobot_example_app_dialog_BUILDTOOL_EXPORT_DEPENDS )
set(promobot_example_app_dialog_EXEC_DEPENDS "libqtpromobot" "libqtapplicationbase" "libqtpromobotdialogmodule")
set(promobot_example_app_dialog_RUN_DEPENDS "libqtpromobot" "libqtapplicationbase" "libqtpromobotdialogmodule")
set(promobot_example_app_dialog_TEST_DEPENDS )
set(promobot_example_app_dialog_DOC_DEPENDS )
set(promobot_example_app_dialog_URL_WEBSITE "http://promo-bot.ru")
set(promobot_example_app_dialog_URL_BUGTRACKER "")
set(promobot_example_app_dialog_URL_REPOSITORY "")
set(promobot_example_app_dialog_DEPRECATED "")