set(_CATKIN_CURRENT_PACKAGE "promobot_app_genpact35")
set(promobot_app_genpact35_VERSION "2.0.0")
set(promobot_app_genpact35_MAINTAINER "promobot <info@promo-bot.ru>")
set(promobot_app_genpact35_PACKAGE_FORMAT "1")
set(promobot_app_genpact35_BUILD_DEPENDS "libqtpromobot" "libqtapplicationbase" "libqtpromobotwidgets" "libqtapplicationwidgets" "libqtpromobotdialogmodule")
set(promobot_app_genpact35_BUILD_EXPORT_DEPENDS "libqtpromobot" "libqtapplicationbase" "libqtpromobotwidgets" "libqtapplicationwidgets" "libqtpromobotdialogmodule")
set(promobot_app_genpact35_BUILDTOOL_DEPENDS "catkin")
set(promobot_app_genpact35_BUILDTOOL_EXPORT_DEPENDS )
set(promobot_app_genpact35_EXEC_DEPENDS "libqtpromobot" "libqtapplicationbase" "libqtpromobotwidgets" "libqtapplicationwidgets" "libqtpromobotdialogmodule")
set(promobot_app_genpact35_RUN_DEPENDS "libqtpromobot" "libqtapplicationbase" "libqtpromobotwidgets" "libqtapplicationwidgets" "libqtpromobotdialogmodule")
set(promobot_app_genpact35_TEST_DEPENDS )
set(promobot_app_genpact35_DOC_DEPENDS )
set(promobot_app_genpact35_URL_WEBSITE "http://promo-bot.ru")
set(promobot_app_genpact35_URL_BUGTRACKER "")
set(promobot_app_genpact35_URL_REPOSITORY "")
set(promobot_app_genpact35_DEPRECATED "")