set(_CATKIN_CURRENT_PACKAGE "promobot_example_app_sip")
set(promobot_example_app_sip_VERSION "2.0.0")
set(promobot_example_app_sip_MAINTAINER "Promobot LLC <info@promo-bot.ru>")
set(promobot_example_app_sip_PACKAGE_FORMAT "1")
set(promobot_example_app_sip_BUILD_DEPENDS "libqtpromobot" "libqtapplicationbase")
set(promobot_example_app_sip_BUILD_EXPORT_DEPENDS "libqtpromobot" "libqtapplicationbase")
set(promobot_example_app_sip_BUILDTOOL_DEPENDS "catkin")
set(promobot_example_app_sip_BUILDTOOL_EXPORT_DEPENDS )
set(promobot_example_app_sip_EXEC_DEPENDS "libqtpromobot" "libqtapplicationbase")
set(promobot_example_app_sip_RUN_DEPENDS "libqtpromobot" "libqtapplicationbase")
set(promobot_example_app_sip_TEST_DEPENDS )
set(promobot_example_app_sip_DOC_DEPENDS )
set(promobot_example_app_sip_URL_WEBSITE "https://promo-bot.ru/sdk")
set(promobot_example_app_sip_URL_BUGTRACKER "")
set(promobot_example_app_sip_URL_REPOSITORY "")
set(promobot_example_app_sip_DEPRECATED "")