set(_CATKIN_CURRENT_PACKAGE "promobot_example_app_js")
set(promobot_example_app_js_VERSION "2.0.0")
set(promobot_example_app_js_MAINTAINER "promobot <info@promo-bot.ru>")
set(promobot_example_app_js_PACKAGE_FORMAT "1")
set(promobot_example_app_js_BUILD_DEPENDS "libqtpromobot" "libqtpromobotwidgets" "libqtapplicationbase" "libqtapplicationwidgets" "libqtpromobotdialogmodule" "libqtpromobotmainscreen" "lightview")
set(promobot_example_app_js_BUILD_EXPORT_DEPENDS "libqtpromobot" "libqtpromobotwidgets" "libqtapplicationbase" "libqtapplicationwidgets" "libqtpromobotdialogmodule" "libqtpromobotmainscreen" "lightview")
set(promobot_example_app_js_BUILDTOOL_DEPENDS "catkin")
set(promobot_example_app_js_BUILDTOOL_EXPORT_DEPENDS )
set(promobot_example_app_js_EXEC_DEPENDS "libqtpromobot" "libqtpromobotwidgets" "libqtapplicationbase" "libqtapplicationwidgets" "libqtpromobotdialogmodule" "libqtpromobotmainscreen" "lightview")
set(promobot_example_app_js_RUN_DEPENDS "libqtpromobot" "libqtpromobotwidgets" "libqtapplicationbase" "libqtapplicationwidgets" "libqtpromobotdialogmodule" "libqtpromobotmainscreen" "lightview")
set(promobot_example_app_js_TEST_DEPENDS )
set(promobot_example_app_js_DOC_DEPENDS )
set(promobot_example_app_js_URL_WEBSITE "http://promo-bot.ru")
set(promobot_example_app_js_URL_BUGTRACKER "")
set(promobot_example_app_js_URL_REPOSITORY "")
set(promobot_example_app_js_DEPRECATED "")