set(_CATKIN_CURRENT_PACKAGE "promobot_example_app_answers")
set(promobot_example_app_answers_VERSION "2.0.0")
set(promobot_example_app_answers_MAINTAINER "promobot <info@promo-bot.ru>")
set(promobot_example_app_answers_PACKAGE_FORMAT "1")
set(promobot_example_app_answers_BUILD_DEPENDS "libqtpromobot" "libqtapplicationbase")
set(promobot_example_app_answers_BUILD_EXPORT_DEPENDS "libqtpromobot" "libqtapplicationbase")
set(promobot_example_app_answers_BUILDTOOL_DEPENDS "catkin")
set(promobot_example_app_answers_BUILDTOOL_EXPORT_DEPENDS )
set(promobot_example_app_answers_EXEC_DEPENDS "libqtpromobot" "libqtapplicationbase")
set(promobot_example_app_answers_RUN_DEPENDS "libqtpromobot" "libqtapplicationbase")
set(promobot_example_app_answers_TEST_DEPENDS )
set(promobot_example_app_answers_DOC_DEPENDS )
set(promobot_example_app_answers_URL_WEBSITE "http://promo-bot.ru")
set(promobot_example_app_answers_URL_BUGTRACKER "")
set(promobot_example_app_answers_URL_REPOSITORY "")
set(promobot_example_app_answers_DEPRECATED "")