set(_CATKIN_CURRENT_PACKAGE "promobot_example_app_emotions")
set(promobot_example_app_emotions_VERSION "2.0.0")
set(promobot_example_app_emotions_MAINTAINER "promobot <info@promo-bot.ru>")
set(promobot_example_app_emotions_PACKAGE_FORMAT "1")
set(promobot_example_app_emotions_BUILD_DEPENDS "libqtpromobot" "libqtapplicationbase")
set(promobot_example_app_emotions_BUILD_EXPORT_DEPENDS "libqtpromobot" "libqtapplicationbase")
set(promobot_example_app_emotions_BUILDTOOL_DEPENDS "catkin")
set(promobot_example_app_emotions_BUILDTOOL_EXPORT_DEPENDS )
set(promobot_example_app_emotions_EXEC_DEPENDS "libqtpromobot" "libqtapplicationbase")
set(promobot_example_app_emotions_RUN_DEPENDS "libqtpromobot" "libqtapplicationbase")
set(promobot_example_app_emotions_TEST_DEPENDS )
set(promobot_example_app_emotions_DOC_DEPENDS )
set(promobot_example_app_emotions_URL_WEBSITE "http://promo-bot.ru")
set(promobot_example_app_emotions_URL_BUGTRACKER "")
set(promobot_example_app_emotions_URL_REPOSITORY "")
set(promobot_example_app_emotions_DEPRECATED "")