set(_CATKIN_CURRENT_PACKAGE "promobot_example_app_camera")
set(promobot_example_app_camera_VERSION "2.0.0")
set(promobot_example_app_camera_MAINTAINER "promobot <info@promo-bot.ru>")
set(promobot_example_app_camera_PACKAGE_FORMAT "1")
set(promobot_example_app_camera_BUILD_DEPENDS "libqtpromobot" "libqtpromobotwidgets" "libqtapplicationbase" "libqtapplicationwidgets")
set(promobot_example_app_camera_BUILD_EXPORT_DEPENDS "libqtpromobot" "libqtpromobotwidgets" "libqtapplicationbase" "libqtapplicationwidgets")
set(promobot_example_app_camera_BUILDTOOL_DEPENDS "catkin")
set(promobot_example_app_camera_BUILDTOOL_EXPORT_DEPENDS )
set(promobot_example_app_camera_EXEC_DEPENDS "libqtpromobot" "libqtpromobotwidgets" "libqtapplicationbase" "libqtapplicationwidgets")
set(promobot_example_app_camera_RUN_DEPENDS "libqtpromobot" "libqtpromobotwidgets" "libqtapplicationbase" "libqtapplicationwidgets")
set(promobot_example_app_camera_TEST_DEPENDS )
set(promobot_example_app_camera_DOC_DEPENDS )
set(promobot_example_app_camera_URL_WEBSITE "http://promo-bot.ru")
set(promobot_example_app_camera_URL_BUGTRACKER "")
set(promobot_example_app_camera_URL_REPOSITORY "")
set(promobot_example_app_camera_DEPRECATED "")