set(_CATKIN_CURRENT_PACKAGE "promobot_example_app_scripts")
set(promobot_example_app_scripts_VERSION "2.0.0")
set(promobot_example_app_scripts_MAINTAINER "promobot <info@promo-bot.ru>")
set(promobot_example_app_scripts_PACKAGE_FORMAT "1")
set(promobot_example_app_scripts_BUILD_DEPENDS "libqtpromobot" "libqtpromobotwidgets" "libqtapplicationbase")
set(promobot_example_app_scripts_BUILD_EXPORT_DEPENDS "libqtpromobot" "libqtpromobotwidgets" "libqtapplicationbase")
set(promobot_example_app_scripts_BUILDTOOL_DEPENDS "catkin")
set(promobot_example_app_scripts_BUILDTOOL_EXPORT_DEPENDS )
set(promobot_example_app_scripts_EXEC_DEPENDS "libqtpromobot" "libqtpromobotwidgets" "libqtapplicationbase")
set(promobot_example_app_scripts_RUN_DEPENDS "libqtpromobot" "libqtpromobotwidgets" "libqtapplicationbase")
set(promobot_example_app_scripts_TEST_DEPENDS )
set(promobot_example_app_scripts_DOC_DEPENDS )
set(promobot_example_app_scripts_URL_WEBSITE "http://promo-bot.ru")
set(promobot_example_app_scripts_URL_BUGTRACKER "")
set(promobot_example_app_scripts_URL_REPOSITORY "")
set(promobot_example_app_scripts_DEPRECATED "")