set(_CATKIN_CURRENT_PACKAGE "promobot_example_app_movement")
set(promobot_example_app_movement_VERSION "2.0.0")
set(promobot_example_app_movement_MAINTAINER "promobot <info@promo-bot.ru>")
set(promobot_example_app_movement_PACKAGE_FORMAT "1")
set(promobot_example_app_movement_BUILD_DEPENDS "libqtpromobot" "libqtpromobotwidgets" "libqtapplicationbase" "libqtapplicationwidgets")
set(promobot_example_app_movement_BUILD_EXPORT_DEPENDS "libqtpromobot" "libqtpromobotwidgets" "libqtapplicationbase" "libqtapplicationwidgets")
set(promobot_example_app_movement_BUILDTOOL_DEPENDS "catkin")
set(promobot_example_app_movement_BUILDTOOL_EXPORT_DEPENDS )
set(promobot_example_app_movement_EXEC_DEPENDS "libqtpromobot" "libqtpromobotwidgets" "libqtapplicationbase" "libqtapplicationwidgets")
set(promobot_example_app_movement_RUN_DEPENDS "libqtpromobot" "libqtpromobotwidgets" "libqtapplicationbase" "libqtapplicationwidgets")
set(promobot_example_app_movement_TEST_DEPENDS )
set(promobot_example_app_movement_DOC_DEPENDS )
set(promobot_example_app_movement_URL_WEBSITE "http://promo-bot.ru")
set(promobot_example_app_movement_URL_BUGTRACKER "")
set(promobot_example_app_movement_URL_REPOSITORY "")
set(promobot_example_app_movement_DEPRECATED "")