set(_CATKIN_CURRENT_PACKAGE "promobot_app_OVE54")
set(promobot_app_OVE54_VERSION "2.0.0")
set(promobot_app_OVE54_MAINTAINER "Catalin Pincu <pincu.catalin@yahoo.com>")
set(promobot_app_OVE54_PACKAGE_FORMAT "1")
set(promobot_app_OVE54_BUILD_DEPENDS "libqtpromobot" "libqtpromobotwidgets" "libqtapplicationbase" "libqtapplicationwidgets")
set(promobot_app_OVE54_BUILD_EXPORT_DEPENDS "libqtpromobot" "libqtpromobotwidgets" "libqtapplicationbase" "libqtapplicationwidgets")
set(promobot_app_OVE54_BUILDTOOL_DEPENDS "catkin")
set(promobot_app_OVE54_BUILDTOOL_EXPORT_DEPENDS )
set(promobot_app_OVE54_EXEC_DEPENDS "libqtpromobot" "libqtpromobotwidgets" "libqtapplicationbase" "libqtapplicationwidgets")
set(promobot_app_OVE54_RUN_DEPENDS "libqtpromobot" "libqtpromobotwidgets" "libqtapplicationbase" "libqtapplicationwidgets")
set(promobot_app_OVE54_TEST_DEPENDS )
set(promobot_app_OVE54_DOC_DEPENDS )
set(promobot_app_OVE54_URL_WEBSITE "www.bucharestrobots.com")
set(promobot_app_OVE54_URL_BUGTRACKER "")
set(promobot_app_OVE54_URL_REPOSITORY "")
set(promobot_app_OVE54_DEPRECATED "")