set(_CATKIN_CURRENT_PACKAGE "promobot_app_genpact_template50")
set(promobot_app_genpact_template50_VERSION "2.0.0")
set(promobot_app_genpact_template50_MAINTAINER "promobot <info@promo-bot.ru>")
set(promobot_app_genpact_template50_PACKAGE_FORMAT "1")
set(promobot_app_genpact_template50_BUILD_DEPENDS "libqtpromobot" "libqtapplicationbase" "libqtpromobotwidgets" "libqtapplicationwidgets" "libqtpromobotdialogmodule")
set(promobot_app_genpact_template50_BUILD_EXPORT_DEPENDS "libqtpromobot" "libqtapplicationbase" "libqtpromobotwidgets" "libqtapplicationwidgets" "libqtpromobotdialogmodule")
set(promobot_app_genpact_template50_BUILDTOOL_DEPENDS "catkin")
set(promobot_app_genpact_template50_BUILDTOOL_EXPORT_DEPENDS )
set(promobot_app_genpact_template50_EXEC_DEPENDS "libqtpromobot" "libqtapplicationbase" "libqtpromobotwidgets" "libqtapplicationwidgets" "libqtpromobotdialogmodule")
set(promobot_app_genpact_template50_RUN_DEPENDS "libqtpromobot" "libqtapplicationbase" "libqtpromobotwidgets" "libqtapplicationwidgets" "libqtpromobotdialogmodule")
set(promobot_app_genpact_template50_TEST_DEPENDS )
set(promobot_app_genpact_template50_DOC_DEPENDS )
set(promobot_app_genpact_template50_URL_WEBSITE "http://promo-bot.ru")
set(promobot_app_genpact_template50_URL_BUGTRACKER "")
set(promobot_app_genpact_template50_URL_REPOSITORY "")
set(promobot_app_genpact_template50_DEPRECATED "")