set(_CATKIN_CURRENT_PACKAGE "promobot_app_template")
set(promobot_app_template_VERSION "2.0.0")
set(promobot_app_template_MAINTAINER "promobot <info@promo-bot.ru>")
set(promobot_app_template_PACKAGE_FORMAT "1")
set(promobot_app_template_BUILD_DEPENDS "libqtpromobot" "libqtapplicationbase")
set(promobot_app_template_BUILD_EXPORT_DEPENDS "libqtpromobot" "libqtapplicationbase")
set(promobot_app_template_BUILDTOOL_DEPENDS "catkin")
set(promobot_app_template_BUILDTOOL_EXPORT_DEPENDS )
set(promobot_app_template_EXEC_DEPENDS "libqtpromobot" "libqtapplicationbase")
set(promobot_app_template_RUN_DEPENDS "libqtpromobot" "libqtapplicationbase")
set(promobot_app_template_TEST_DEPENDS )
set(promobot_app_template_DOC_DEPENDS )
set(promobot_app_template_URL_WEBSITE "http://promo-bot.ru")
set(promobot_app_template_URL_BUGTRACKER "")
set(promobot_app_template_URL_REPOSITORY "")
set(promobot_app_template_DEPRECATED "")