set(_CATKIN_CURRENT_PACKAGE "promobot_app_templateui")
set(promobot_app_templateui_VERSION "2.0.0")
set(promobot_app_templateui_MAINTAINER "promobot <info@promo-bot.ru>")
set(promobot_app_templateui_PACKAGE_FORMAT "1")
set(promobot_app_templateui_BUILD_DEPENDS "libqtpromobot" "libqtpromobotwidgets" "libqtapplicationbase")
set(promobot_app_templateui_BUILD_EXPORT_DEPENDS "libqtpromobot" "libqtpromobotwidgets" "libqtapplicationbase")
set(promobot_app_templateui_BUILDTOOL_DEPENDS "catkin")
set(promobot_app_templateui_BUILDTOOL_EXPORT_DEPENDS )
set(promobot_app_templateui_EXEC_DEPENDS "libqtpromobot" "libqtpromobotwidgets" "libqtapplicationbase")
set(promobot_app_templateui_RUN_DEPENDS "libqtpromobot" "libqtpromobotwidgets" "libqtapplicationbase")
set(promobot_app_templateui_TEST_DEPENDS )
set(promobot_app_templateui_DOC_DEPENDS )
set(promobot_app_templateui_URL_WEBSITE "http://promo-bot.ru")
set(promobot_app_templateui_URL_BUGTRACKER "")
set(promobot_app_templateui_URL_REPOSITORY "")
set(promobot_app_templateui_DEPRECATED "")